### ISSUE TITLE
animated artwork as condition for text labels

### ISSUE THREAD

**Issue by Joostzilla** [jeroenpardon/skin.grid#141] opened 2017-10-22 12:44 UTC
In Movies landscape view some fanart have the title shown by Grid while others have not. If the fanart does not have the movies title as part of the fanart it is hard to see which movie it is.

![image](https://user-images.githubusercontent.com/1034920/31862022-66c3d334-b737-11e7-8f48-77e08c226ac1.png)

**Comment by jeroenpardon** [comment] 2017-10-22 13:12
It all depends on what your landscape artwork type is set to and whether you have logo's enabled.

Artwork type set to prefer landscape thumbnails
- Landscape thumbnail available: don't show text based titles (as landscape thumbnails have logo's incorporated in the artwork)
- No landscape thumbnail available: artwork falls back to fanart, text based titles are used because fanart usually does not have logo's incorporated (and it shouldn't!)

Artwork set to prefer fanart
- Logo's enabled and logo is available for the movie or show: text based titles are used because of the logo
- Logo's enabled and no logo available: text based titles are used
- Logo's disabled: text based titles are used

**Comment by Joostzilla** [comment] 2017-10-22 13:21
That's clear. What an options 👍 
I will have to get used to the power of Kodi.
Since i prefer Landscape thumbnail i now have logo's enabled. Does this add text based titles as fallback when no landscape or logo is available?

**Comment by Joostzilla** [comment] 2017-10-22 13:32
I found out that the text based titles do not appear on Animated art.

**Comment by jeroenpardon** [comment] 2017-10-22 13:38
Hm, right. That would be a oversight :)

**Comment by jeroenpardon** [comment] 2017-10-22 13:43
>Since i prefer Landscape thumbnail i now have logo's enabled. Does this add text based titles as fallback when no landscape or logo is available?

It should yes.

**Comment by Joostzilla** [comment] 2017-10-22 13:46
But it does not yet ;-)

**Comment by jeroenpardon** [comment] 2017-10-22 13:56
I was doubting myself when posting ;P So I just checked the code, and logos are basically not a factor currently when the artwork is set to landscape. The fallback routine is landscape images > fanart + text title

It might seem a trivial thing, but the way it currently is is already quite complex. I think in most cases a landscape image will be available so I'm not looking to increase the complexity here (note though that you may not get landscape artwork currently because of issues with the artwork downloader add-on.

**Comment by Joostzilla** [comment] 2017-10-22 14:03
For me its no problem. Most movies have landscape thumbs or animated art.
Since i manage my media with TinyMediaManager and use Plex it already has 99% of the art available in the media folders.
And i am still trying to figure out which view i prefer for browsing for movies. Which do you use?

**Comment by jeroenpardon** [comment] 2017-10-23 05:42
> I found out that the text based titles do not appear on Animated art.

I just checked this, but with animated artwork turned on, I am seeing text based titles? Is this in particular viewtypes for you?

> And i am still trying to figure out which view i prefer for browsing for movies. Which do you use?

For movies it's pretty much list view all the way with the exception of the recently added movies node and watchlist where I use Gallery.

**Comment by Joostzilla** [comment] 2017-10-23 10:14
Okay, what i found out i this: (all in landscape view)

- prefer Fanart: Text based titles show on every image. Also on Animated art.
- prefer Fanart + Logo's: no text based titles
- prefer Landscape thumbnails: Only text based titles on missing Landscape thumb. Not on Animated art.

Turning off Animated Art isn't possible on a global scale. Is it?

**Comment by jeroenpardon** [comment] 2017-10-23 10:59
Yeah, so that basically works as intended, if animated fanart is not taking into account. I think it should be doable to create an exception rule based on whether or not animated artwork is being displayed. I think...will have to look into it.

> Turning off Animated Art isn't possible on a global scale. Is it?

You mean, not showing it at all? Sure, it's an optional feature.

**Comment by Joostzilla** [comment] 2017-10-23 11:16
> You mean, not showing it at all? Sure, it's an optional feature.
Really, where do i find the option

**Comment by jeroenpardon** [comment] 2017-10-23 11:57
Skin Settings -> Visual effects

But I'm pretty sure it's off by default ;)

**Comment by Joostzilla** [comment] 2017-10-23 12:07
>Skin Settings -> Visual effects
But I'm pretty sure it's off by default ;)

Of course i knew it was there. Somehow i thought it was for homescreen only. Blackout ;-)

**Comment by jeroenpardon** [comment] 2017-10-24 19:06
Closing this. Before delving into this further let's see if animated artwork is even a lasting thing.

**Closed by jeroenpardon** 2017-10-24 19:06 UTC
Labels: Enhancement, Optimization
